[project]
name = "activator"
version = "0.1.0"
description = ""
authors = [
    {name = "Noam Shabtai",email = "shabtai.noam@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "system @ file:///home/noam/version_control/portfolio/signal_processing/system",
    "matplotlib (>=3.10.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
parse-sweeps = {path = "../parse_sweeps", develop = true}
data-handle = {path = "../data_handle", develop = true}
ipdb = "^0.13.13"


[tool.poetry.dependencies]
system = {develop = true}
