[project]
name = "activator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "data-handle",
    "matplotlib>=3.10.0",
    "system",
    "wraplogging",
]

[dependency-groups]
dev = [
    "parse-sweeps",
    "pytest>=8.3.4",
]

[tool.uv.sources]
parse-sweeps = { path = "../parse_sweeps", editable = true }
system = { path = "../system", editable = true }
data-handle = { path = "../data_handle", editable = true }
wraplogging = { path = "../wraplogging", editable = true }

[tool.setuptools.packages.find]
exclude = ["output"]
