[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pre-commit = "^4.1.0"
parse-sweeps = {path = "parse_sweeps", develop = true}
activator = {path = "activator", develop = true}
data-handle = {path = "data_handle", develop = true}


[tool.poetry.dependencies]
system = {develop = true}

[project]
name = "signal-processing"
version = "0.1.0"
description = ""
authors = [
    {name = "Noam Shabtai",email = "shabtai.noam@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "system @ file:///home/noam/version_control/portfolio/signal_processing/system"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
