[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pre-commit = "^4.1.0"


[tool.poetry.dependencies]
parse-sweeps = {develop = true}
buffer = {develop = true}
[project]
name = "signal-processing"
version = "0.1.0"
description = ""
authors = [
    {name = "Noam Shabtai",email = "shabtai.noam@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "parse-sweeps @ file:///home/noam/version_control/portfolio/signal_processing/parse_sweeps",
    "buffer @ file:///home/noam/version_control/portfolio/signal_processing/buffer"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
